metadata:
  tmdb_api_key: ""

spotify:
  client_id: ""
  client_secret: ""

discogs:
  token: ""

ncore:
  upload_url: "https://ncore.pro/upload.php"

torrent:
  announce_url: ""

auth:
  cookies_file: "auth/ncore.txt"

paths:
  torrent_output: "work/torrents"
  nfo_output: "work/nfo"
  techinfo_output: "work/techinfo"
  images_output: "work/images"
  screenshots_output: "work/screenshots"
  downloaded_torrents: "work/downloaded_torrents"
